add_subdirectory(HMSHodoscope)

set(DETECTOR_TRANSLATOR_LIBS
    hms_hodoscope_translator
    PARENT_SCOPE
)

set(DETECTOR_TRANSLATOR_INCLUDE_DIRS
    ${HMS_HODOSCOPE_TRANSLATOR_INCLUDE_DIRS}
    PARENT_SCOPE
)

set(DETECTOR_TRANSLATOR_HEADERS
    ${HMS_HODOSCOPE_TRANSLATOR_PUBLIC_HEADERS}
    PARENT_SCOPE
)
