add_subdirectory(FADC)

set(HMS_TRANSLATOR_LIBS
    hms_hodoscope_fadc_translator
    PARENT_SCOPE
)

set(HMS_TRANSLATOR_INCLUDE_DIRS
    ${HMS_HODOSCOPE_FADC_TRANSLATOR_INCLUDE_DIRS}
    PARENT_SCOPE
)

set(HMS_TRANSLATOR_HEADERS
    ${HMS_HODOSCOPE_FADC_TRANSLATOR_PUBLIC_HEADERS}
    PARENT_SCOPE
)
